baseurl: ""
url: "https://www.mgarcia.info"
exclude: ['README.md', 'CNAME', '.gitignore']
maps_api: "AIzaSyA-swbMmPLMu9vAKjDlpSs8CAr2fxK7lp8"
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en", "es"]
exclude_from_localizations: ["assets", "images"]
